apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-project-cloud-devops
  labels:
    app: capstone-project-cloud-devops
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone-project-cloud-devops
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: capstone-project-cloud-devops
    spec:
      containers:
        - image: sudarshanas/capstone:latest
          imagePullPolicy: Always
          name: capstone-project-cloud-devops
          ports:
            - name: web
              containerPort: 80
              protocol: TCP
              
---
apiVersion: v1
kind: Service
metadata:
  name: capstone-project-cloud-devops
spec:
  selector:
    app: capstone-project-cloud-devops
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
  type: LoadBalancer
